[[stack]]
name = "{{ stack_name }}"

[stack.config]
server = "{{ server_name }}"
file_paths = [ "docker-compose.yaml" ]
{%- if has_git %}
run_directory = "{{ stack_name }}"
git_provider = "github.com"
repo = "shahvirb/{{ stack_name }}"
{%- else %}
files_on_host = true
{%- endif %}
{% if op_unpack %}
[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"
{% endif %}
